<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="2" failures="0" skipped="0" tests="2" time="1.751" timestamp="2024-05-17T17:29:12.427816" hostname="automation"><testcase classname="" name="tests.test_chrome_kiosk" time="0.000"><error message="collection failure">ImportError while importing test module '/home/ansible/.local/share/dasbootstrap/tests/test_chrome_kiosk.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.venv/lib/python3.11/site-packages/_pytest/python.py:487: in importtestmodule
    mod = import_path(
../.venv/lib/python3.11/site-packages/_pytest/pathlib.py:591: in import_path
    importlib.import_module(module_name)
../../../../.pyenv/versions/3.11.8/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1204: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1176: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1147: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:690: in _load_unlocked
    ???
../.venv/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
test_chrome_kiosk.py:4: in &lt;module&gt;
    from pyprojects.chrome_kiosk.chrome import ChromeKiosk
../pyprojects/chrome_kiosk/chrome.py:8: in &lt;module&gt;
    from pynput import keyboard
../.venv/lib/python3.11/site-packages/pynput/__init__.py:40: in &lt;module&gt;
    from . import keyboard
../.venv/lib/python3.11/site-packages/pynput/keyboard/__init__.py:31: in &lt;module&gt;
    backend = backend(__name__)
../.venv/lib/python3.11/site-packages/pynput/_util/__init__.py:77: in backend
    raise ImportError('this platform is not supported: {}'.format(
E   ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))
E   
E   Try one of the following resolutions:
E   
E    * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly</error></testcase><testcase classname="" name="" time="0.000"><error message="collection failure">../.venv/lib/python3.11/site-packages/pluggy/_hooks.py:513: in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
../.venv/lib/python3.11/site-packages/pluggy/_manager.py:120: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
../.venv/lib/python3.11/site-packages/_pytest/main.py:648: in pytest_collectstart
    raise self.Failed(self.shouldfail)
E   _pytest.main.Failed: stopping after 1 failures</error></testcase></testsuite></testsuites>